### ISSUE TITLE
Use self signed certificates

### ISSUE THREAD

**Issue by snaggen** [LucasPickering/slumber#109]
Use of self signed or invalid certificates are common in dev environmnts. But I cannot find anything in the docs about how to tell slumber to ignore certificate errors, and when I tried to contact a server with a root cert not in the trusted chain I get:
```
invalid peer certificate: UnknownIssuer
```
It would be nice if this could be documented if it is possible already, or implemented if not currently possible.

**Comment by LucasPickering** [comment]
This is not possible, but *shouldn't* be too hard to add

**Comment by LucasPickering** [comment]
After thinking about this a little more, I want to be very narrow about how this is enabled so someone doesn't enable it for all hostnames then accidentally fall victim to a MITM attack. Currently I'm thinking of adding a field to the root [Collection](http://127.0.0.1:7979/book/api/request_collection.html#fields) type called `allow_invalid_cert_hostnames`, like so:

```yaml
allow_invalid_cert_hostnames: ["127.0.0.1", "dev.test.website"]
```

This would leave cert checking on for all _other_ hostnames, and only disable it for the ones explicitly listed. This would be an exact match based on the hostname in the URL, so **no** regex/wildcard support.

@snaggen Would this satisfy your need?

**Comment by snaggen** [comment]
But in my case it wasn't the hostname, but that the root certificate is not in the system store. So, I need a flag that disable any certificate checks for the specific hosts
