### ISSUE TITLE
Add `trim` option to command chains

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/slumber#153]
Add a field `trim` to the `command` chain source, which trims whitespace from the ends of the **output** string. It's pretty common to have shell commands that include a useless trailing newline, in which case you have to do something like `command: [sh, -c, "<cmd> | tr -d '\n'"]`

Worth considering: instead of just a boolean, should just be an enum? `none`, `start`, `end`, `both`?

## Implementation

- Field should be added in [models.rs](https://github.com/LucasPickering/slumber/blob/5b164ac515ed37a78707df2e567299915ad90bc9/src/collection/models.rs#L210) 
- Implementation in [render.rs](https://github.com/LucasPickering/slumber/blob/5b164ac515ed37a78707df2e567299915ad90bc9/src/template/render.rs#L438)
- Documentation in [chain_source.md](https://raw.githubusercontent.com/LucasPickering/slumber/master/docs/src/api/request_collection/chain_source.md)

**Comment by Sammo98** [comment]
@LucasPickering I'd be keen to pick this one up as well, unless anyone else had plans to?
