### ISSUE TITLE
Make it easier to use shell commands

### ISSUE THREAD

**Issue by LucasPickering** [LucasPickering/slumber#166]
In some cases, you want a chain to be a shell command rather than a native one. Right now you can do this with something like:

```yaml
chains:
  example:
    source: !command
      command: ["sh", "-c", "echo 'hello' | grep 'he'"]
```

This is a bit clunky though. A more friendly alternative may be:

```yaml
chains:
  example:
    source: !shell
      command: "echo 'hello' | grep 'he'"
      shell: sh
```

The main question though is: **which shell to use by default?** Some options:
- Always `sh` (it's simple and everyone has it)
- System default
  - This could cause issues based on what shell a user has
- Always require the `shell` field
  - I would prefer this option, it's more explicit

This raises issues of compatibility with windows though.

## Implementation

- New `ChainSource` variant needs to be added in [models.rs](https://github.com/LucasPickering/slumber/blob/5b164ac515ed37a78707df2e567299915ad90bc9/src/collection/models.rs#L201)
- Implementation in [render.rs](https://github.com/LucasPickering/slumber/blob/5b164ac515ed37a78707df2e567299915ad90bc9/src/template/render.rs#L431), similar to the existing `render_command` function
- Documentation in [chain_source.md](https://raw.githubusercontent.com/LucasPickering/slumber/master/docs/src/api/request_collection/chain_source.md)

**Comment by Aloso** [comment]
> Always `sh` (it's simple and everyone has it)

On Linux and macOS, yes, but not on Windows.

To make shell commands work cross-platform, Deno made [`deno_task_shell`](https://github.com/denoland/deno_task_shell/) ([documentation](https://docs.deno.com/runtime/manual/tools/task_runner#syntax)).

By the way, you don't need a way to change the default shell. In the (probably very few) cases where deno_task_shell is not sufficient, a different shell can be invoked:

**Comment by LucasPickering** [comment]
I'm hesitant to bake an entire shell implementation into the Slumber binary for a niche feature that is largely just a QoL improvement. I was sort of on the fence about this being a feature because I wasn't sure if the convenience justified the added complexity. Now that you point at the cross-platform issues I'm leaning even more toward not doing this.

And a point of clarification: this would add a *new* chain source type called `!shell`, in addition to the existing `!command` which invokes a command directly. `!command` already allows users to invoke a specific shell of their choosing. That of course has the same cross-platform concerns as if we support shells in Slumber, but it at least pushes that problem into user-space. In reality I'm not sure how many projects will have a shared Slumber config used on multiple platforms that need a complex shell command anyway.

**Comment by Aloso** [comment]
> I wasn't sure if the convenience justified the added complexity

That is unfortunate, because without it, `!command` is hardly usable in a cross-platform way. The following example

```yml
chains:
  example:
    source: !command
      command: ["sh", "-c", "echo 'hello' | grep 'he'"]
```

doesn't work on Windows either. I didn't think adding deno_task_shell would be a problem, since it is tiny (compared to proper shells like `bash` or `zsh`) and very well maintained by the Deno folks.

**Comment by LucasPickering** [comment]
You could use an external tool to provide the cross-platform support needed, then call out to that from Slumber. FRom a quick search, it looks like [cargo-make](https://github.com/sagiegurari/cargo-make) supports a few different ways of making cross-platform commands, as an example. 

`deno_task_shell` looks cool but based on the complete lack of documentation for the crate itself, I get the sense it's not intended to be used directly as a dependency. I agree that support this inline would be useful, but I'm trying to limit scope creep here so I'm going to close this. If there's a significant amount of demand for this I'll reconsider.
