### ISSUE TITLE
Install docs mention env-select instead of slumber

### ISSUE THREAD

**Issue by andreinonea** [LucasPickering/slumber#179]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**

Yes.

**Describe the bug**
_A clear and concise description of what the bug is_

Installation docs via `cargo` or `binstall` are referring to `env-select` instead of `slumber`.

**To Reproduce**
_Steps to reproduce the behavior_

1. Go to https://slumber.lucaspickering.me/ or https://slumber.lucaspickering.me/artifacts

**Expected behavior**
_A clear and concise description of what you expected to happen_

Install step is `cargo install slumber` instead?

**Screenshots**
_If applicable, add screenshots to help explain your problem_

![image](https://github.com/LucasPickering/slumber/assets/34586490/c90e2fb8-7f8e-4f8a-916c-2182802e7689)

**Version (please complete the following information):**

- OS: N/A
- Terminal: N/A
- Slumber Version: N/A

**Additional context**

No more context, it's just a very tiny issue that I observed while wanting to install `slumber`. Thank you for the nice work on it!

**Comment by LucasPickering** [comment]
Oops! Copy pasted from another project and forgot to change it. Thank you!
