### ISSUE TITLE
Installing Slumber causes error: unresolved imports `signal_hook::consts::SIGHUP`, `signal_hook::consts::SIGQUIT`, `signal_hook::iterator`

### ISSUE THREAD

**Issue by Bryson14** [LucasPickering/slumber#180]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**
Yes

**Describe the bug**
I am running on windows and opened the terminal. In git bash, I ran `cargo install slumber`. 

The app downloaded and started to compile. On the last step, I got this error:

```
 Compiling hyper v0.14.28
   Compiling hyper-rustls v0.24.2
   Compiling reqwest v0.11.27
   Compiling slumber v1.0.0
error[E0432]: unresolved imports `signal_hook::consts::SIGHUP`, `signal_hook::consts::SIGQUIT`, `signal_hook::iterator`
  --> C:\Users\22\.cargo\registry\src\index.crates.io-6f17d22bba15001f\slumber-1.0.0\src\tui.rs:29:14
   |
29 |     consts::{SIGHUP, SIGINT, SIGQUIT, SIGTERM},
   |              ^^^^^^          ^^^^^^^ no `SIGQUIT` in `consts`
   |              |
   |              no `SIGHUP` in `consts`
30 |     iterator::Signals,
   |     ^^^^^^^^ could not find `iterator` in `signal_hook`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `slumber` (bin "slumber") due to 1 previous error
error: failed to compile `slumber v1.0.0`, intermediate artifacts can be found at `C:\Users\22~1\AppData\Local\Temp\cargo-installJnLI65`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**To Reproduce**
_Steps to reproduce the behavior_

1.

**Expected behavior**
_A clear and concise description of what you expected to happen_

**Screenshots**
_If applicable, add screenshots to help explain your problem_

**Version (please complete the following information):**
- Cargo 1.77.0
- rustc 1.77.0

- OS:
- Terminal: GitBash
- Slumber Version:

**Additional context**

**Comment by Bryson14** [comment]
Running it within powershell results in the same issue

**Comment by Bryson14** [comment]
Installing slumber on WSL 2 (ubuntu) was sucessful.

**Comment by LucasPickering** [comment]
@Bryson14 I just merged a fix for the build on Windows. Do you mind trying it out? You can install the master branch with:

```
cargo install --git https://github.com/LucasPickering/slumber
```

If that works I'll put out a release.

**Comment by Bryson14** [comment]
That worked on Windows!
