### ISSUE TITLE
feature request: Improve Auto Detect `slumber.yaml`

### ISSUE THREAD

**Issue by kristopherbullinger** [LucasPickering/slumber#194]
# Motivation
If the user wishes to use slumber in a directory where a `slumber.yaml` file is not present, slumber will fail to start with an error unless the user specifies the location manually. This is inconvenient unless the user happens to be working in the same directory that their `slumber.yaml` is defined.

# Feature Description
Allow slumber to check the current directory as it currently does, but instead of terminating on failing to find the config file in the current directory, check the parent directories in order until the root is reached (upon which slumber terminates) or a `slumber.yaml` is found.

# Prior Art
[dotenvy](https://docs.rs/dotenvy/0.15.7/dotenvy/fn.dotenv.html)

# Note
As the location of the detected config file may be less apparent to the user, I suggest adding a diagnostic message at the bottom of the TUI declaring the location of the `slumber.yaml` file which was detected, similar to when slumber reloads upon detecting a change to the config file.
```
[13:33:11] Loaded collection from /user/abcdefghi/slumber.yaml
```

**Comment by LucasPickering** [comment]
Thanks for the suggestion, just put up a PR. Also FWIW you can check the collection file path any time in the help menu `?` in the TUI:

![image](https://github.com/LucasPickering/slumber/assets/2382935/7286b514-46b7-4471-bf6e-d91b3fb0a88a)
