### ISSUE TITLE
Add slumber to Scoop

### ISSUE THREAD

**Issue by renatocfrancisco** [LucasPickering/slumber#267]
feat: Adding slumber in [Scoop](https://scoop.sh/)'s buckets.
I think it would be cool.
If i can install pnpm using the powershell method and with scoop, i think slumber can benefit from this.

**Comment by LucasPickering** [comment]
Slumber relies on cargo-dist to build distributables in various formats. It looks like there's an [open issue](https://github.com/axodotdev/cargo-dist/issues/521) in cargo-dist for Scoop support, but no one over there has stepped up to work on it. This isn't something I have time to work on, but if you or someone else wants to take on that work I'd be happy to enable it in Slumber once it's available.

**Comment by aliesbelik** [comment]
https://scoop.sh/#/apps?q=slumber
