### ISSUE TITLE
`cargo install slumber` doesn't work

### ISSUE THREAD

**Issue by popzxc** [LucasPickering/slumber#319]
**Did you [search](https://github.com/LucasPickering/slumber/issues) for existing issues already?**

Yes

**Describe the bug**

`cargo install slumber` currently fails to compile the crate. I've tried with both rustc 1.79 and 1.80.1.

Output (trimmed):

```
error[E0277]: `<K as PersistedKey>::Value` doesn't implement `Debug`
   --> /home/<...>/.cargo/registry/src/index.crates.io-6f17d22bba15001f/persisted-0.1.1/src/lib.rs:214:10
    |
214 | #[derive(derive_more::Debug, Display)]
    |          ^^^^^^^^^^^^^^^^^^ `<K as PersistedKey>::Value` cannot be formatted using `{:?}` because it doesn't implement `Debug`
    |
    = help: the trait `Debug` is not implemented for `<K as PersistedKey>::Value`, which is required by `&core::option::Option<<K as PersistedKey>::Value>: Debug`
    = note: required for `core::option::Option<<K as PersistedKey>::Value>` to implement `Debug`
    = note: 1 redundant requirement hidden
    = note: required for `&core::option::Option<<K as PersistedKey>::Value>` to implement `Debug`
    = note: required for the cast from `&&core::option::Option<<K as PersistedKey>::Value>` to `&dyn Debug`
    = note: this error originates in the derive macro `derive_more::Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `persisted` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `slumber v1.7.0`, intermediate artifacts can be found at `/tmp/cargo-installgiKN8V`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path
```

**To Reproduce**
_Steps to reproduce the behavior_

1. `cargo install slumber`

**Expected behavior**
_A clear and concise description of what you expected to happen_

`slumber` is installed.

**Screenshots**
_If applicable, add screenshots to help explain your problem_

Output is provided above.

**Version (please complete the following information):**

- OS: Win11/WSL2
- Terminal: VS code
- Slumber Version: Latest

**Additional context**

**Comment by LucasPickering** [comment]
An unfortunate feature of cargo is that `cargo install` [ignore's the installed packages `Cargo.lock`](https://doc.rust-lang.org/cargo/commands/cargo-install.html#dealing-with-the-lockfile), which means breaking changes can slip through. You should be able to install with:

```
cargo install slumber --locked
```

I'll update the docs to use `--locked` in the command and work on fixing this.
