### ISSUE TITLE
Open response body in pager

### ISSUE THREAD

**Issue by ttytm** [LucasPickering/slumber#404]
**Feature Description**

Similar how the `Edit Collection` action opens the collection file in an editor, it would be great to have the ability to open a body in a pager which can be specified via the config or an environment variable.

For example, what I'm current getting from https://github.com/antonmedv/fx is the ability regexp-search in a body - independently of knowing it's keys - and to get further information about it's contents - like sizes of objects and arrays.

Ref.:
![Screenshot_20241022_001203](https://github.com/user-attachments/assets/50f88c3f-9ba5-40ce-bf8f-a2a880e3ffce)

It also allows for folding, which is related to providing a solution for #398

Features like this might become native in slumber one day. Until then users wouldn't have to make compromises when having the possibility of using an additional viewer directly from within slumber.

**Additional Context**

For example the [posting](https://github.com/darrenburns/posting) python project allows to specify a regular pager, and a json_pager.

**Comment by LucasPickering** [comment]
I love this idea, also `fx` looks great and I'm gonna start using it. This shouldn't be too hard since we can reuse the machinery for opening in an editor. I'll get started on it soon.

**Comment by LucasPickering** [comment]
@ttytm I have an initial implementation merged to `master`. I'd like to get someone else's hands on it before releasing though. Do you mind trying it out? In your config file you can set `viewer: fx`, similar to the editor command. 

I didn't support per-language viewers yet, but deifnitely plan to. I just wanted to get an initial version out before jumping back onto some previous work.

**Comment by ttytm** [comment]
Sorry the delay @LucasPickering,

I had checked out the PR branch and used it as soon as I have seen it. 
IMHO it's already a very useful feature as it is. Thanks for the efforts!
