### ISSUE TITLE
Preserve original sorting

### ISSUE THREAD

**Issue by ttytm** [LucasPickering/slumber#405]
Currently, JSON bodies are sorted alphabetically by their key names. It would be great to have it at least configurable to keep the original sorting. It might yield the more expected result if sorting is opt-in.

**Comment by LucasPickering** [comment]
This is definitely a bug, I just never noticed because I always test with [httpbin.org](https://httpbin.org), which always sorts JSON responses alphabetically anyway. It's a simple fix.
