### ISSUE TITLE
feature may not be used on the stable release channel

### ISSUE THREAD

**Issue by 0323pin** [LucasPickering/slumber#42]
Hi,

`Cargo.toml` states `rust-version = "1.72.0"` but, compiling `slumber` using Rust-1.73 yields the following:

```
   Compiling slumber v0.7.0 (/usr/pkgsrc/wip/slumber/work/slumber-0.7.0)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:2:1
  |
2 | #![feature(associated_type_defaults)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:3:1
  |
3 | #![feature(iterator_try_collect)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:4:1
  |
4 | #![feature(lazy_cell)]
  | ^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:5:1
  |
5 | #![feature(trait_upcasting)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:6:1
  |
6 | #![feature(try_blocks)]
  | ^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:3:12
  |
3 | #![feature(iterator_try_collect)]
  |            ^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:4:12
  |
4 | #![feature(lazy_cell)]
  |            ^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `slumber` (bin "slumber") due to 7 previous errors
*** Error code 101

Stop.
```

So, what's the MSRV for this project?

**Comment by LucasPickering** [comment]
Sorry about that, I forgot to remove the MSRV when I switched to nightly. Right now it will only build on nightly. I'm in the process of refactoring pretty much the entire app, and in the process I'm going to try to get it back on stable.

**Comment by 0323pin** [comment]
Ok, thanks!

**Comment by LucasPickering** [comment]
I just merged [a PR](https://github.com/LucasPickering/slumber/pull/48) to get back on the stable channel (1.74). None of the nightly features being used were strictly necessary. I'm running a release now so 0.8 will run on stable.

**Comment by 0323pin** [comment]
Thanks! I'll try it later today. If it works, I'll package it for NetBSD and commit it to the **W**ork **I**n **P**rogress repository.

Can't commit to main straight away because, NetBSD is generally on stable minus one when it comes to Rust. 1.74 will most probably be merged a few days after 1.75 is released. My machine, on the other hand is nearly always on the latest stable.

**Comment by 0323pin** [comment]
@LucasPickering It works just fine, http://mail-index.netbsd.org/pkgsrc-wip-changes/2023/11/22/msg028687.html

**Comment by 0323pin** [comment]
@LucasPickering merged into the main branch, https://mail-index.netbsd.org/pkgsrc-changes/2024/01/07/msg290420.html

I'll update it to 0.12.0 very soon.

**Comment by 0323pin** [comment]
0.12.0 [merged](https://mail-index.netbsd.org/pkgsrc-changes/2024/01/11/msg290615.html)
